config/routes.rb
Rails.application.routes.draw do

  resources :range_subventions
  resources :addresses
  resources :notification_effects
  get 'calendar/index'

  # Public resources
  root to: 'homepage#index', format: false
  
  
  get 'authorize' => 'auth#gettoken'
  get '/redirect', to: 'events#redirect', as: 'redirect'
  get '/callback', to: 'events#callback', as: 'callback'
  get '/calendars', to: 'events#calendars', as: 'calendars'

  get '/lang/:lang', to: 'application#change_language', as: 'change_language'
  get '/show/:id', to: 'visitors#show', as: 'show'
  get '/update_holders', to: 'visitors#update_holders', as: 'update_holders'
  get '/inicio.do', to: 'uweb_access#uweb_sign_in'
  get '/agenda/:holder/:full_name', to: 'visitors#agenda', as: 'agenda'

  get '/faq', to: 'questions#index', as: 'faq'
  get '/websitemap', to: 'static_pages#websitemap', as: 'websitemap'

  post '/ws/agends', to: 'ws/agends#generic'
  post '/ws/agends/:personal_code', to: 'ws/agends#holder'

  resources :statistics, only: [:index]
  resources :statistics do
    get :lobbies, on: :collection
  end

  get '/code_of_conduct', to: 'static_pages#code_of_conduct', as: 'code_of_conduct'
  get '/accessibility', to: 'static_pages#accessibility', as: 'accessibility'

  get '/homepage', to: 'homepage#index', as: 'homepage'
  get 'registration_lobbies/index'
  get '/registration_lobbies', to: 'registration_lobbies#index', as: 'registration_lobbies'
  get '/visitors', to: 'visitors#index', as: 'visitors'
  get '/export_events', to: 'visitors#export_events', as: 'visitors_export_events'

  # Admin
  get "/admin", to: 'events#index', as: 'admin'
  
  #namespace :api do
    wash_out :servicio_integracion_bareg
  #end
  

  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :events do
    get :download, on: :collection
    get :clone, on: :member
    get :export_outlook, on: :member
    get :get_calendars, on: :member
  end
  
 
  resources :areas
  resources :activities
  resources :infringement_emails, only: [:new, :create]
  resources :holders do 
    get :active, on: :collection
    get :mail, on: :member
    post :send_mail, on: :member
    get :export_all, on: :collection
    get :search, on: :collection
  end


  namespace :admin do
    resources :notifications, except: [:index, :new, :create, :destroy] do 
      get :active, on: :collection
      get :historic, on: :collection
      get :pre_recover, on: :member
      post :recover, on: :member
      get :pre_canceled, on: :member
      post :canceled, on: :member
      get :permited, on: :member
      get :manually_permited, on: :member
      get :recover_origin, on: :member
      post :update_notification, on: :member
    end
    resources :exports
    resources :parametrizations, only: [:index] do
      post :change_view, on: :collection
      post :length_event_description, on: :collection
      post :send_email, on: :collection
      post :update_configure_text, on: :member
      get :download_log
    end
    resources :manage_emails
    resources :users do 
      get :revert, on: :member
      get :assign_holder, on: :collection
      get :export_manages, on: :collection
      get :uweb, on: :collection
    end
    get 'passwords/edit', to: 'passwords#edit', as: 'edit_password'
    match 'passwords/update', to: 'passwords#update', as: 'update_password', via: [:patch, :put]
    resources :organizations do
      resources :agents
      resources :organization_interests, only: [:index]
      match 'interests_update', to: 'organization_interests#update', as: 'interests_update', via: [:patch, :put]
    end
    resources :organizations_links
    resources :questions
    post 'order_questions', to: 'questions#order', as: 'order_questions'

    resources :newsletters do
      member do
        post :deliver
      end
      get :users, on: :collection
    end
  end

  resources :positions do
    get :autocomplete_position_title, :on => :collection
  end
  get '/organizations/edit', to: 'organizations#edit', as: 'edit_organization'
  get '/organizations/destroy', to: 'organizations#destroy', as: 'destroy_organization'
  get '/organizations/new', to: 'organizations#new', as: 'new_organization'
  resources :organizations, except: [:new, :edit, :destroy] do
    get :autocomplete_organization_name, :on => :collection
    resources :represented_entities, only: :index, format: :json
    resources :agents, only: :index, format: :json
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get '*path' => redirect { |p, req| req.flash[:alert] = "No se encuentra la ruta especificada"; '/' } unless Rails.env.development?

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def accessibility
  rescue => e
    begin
      Rails.logger.error("COD-00001: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def websitemap
  rescue => e
    begin
      Rails.logger.error("COD-00002: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def code_of_conduct
  rescue => e
    begin
      Rails.logger.error("COD-00003: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end
end

app/views/static_pages/accessibility.html.erb
<%=ConfigureText.find_by(code: 'content_accesibility').try(:content_body).to_s.html_safe%>

app/views/static_pages/code_of_conduct.html.erb
<% content_for(:body_class) { 'visit-code-of-conduct' } %>

<div class="conduct_code small-12 column">
  <%= link_to t('backend.back'), registration_lobbies_path , :class=> "button tiny radius" %>
  <p style="margin-top: 2rem">La inscripción en el Registro de Lobbies lleva aparejado el compromiso de que quien se inscribe va a ajustar su actuación a un código de conducta que ya contempla la propia Ordenanza de Transparencia de la Ciudad de Madrid. Su artículo 37 enumera las obligaciones que integran este código:</p>
  <ol type="a">
    <li>Aceptar que la información proporcionada se haga pública.</li>
    <li>No obtener ni tratar de obtener la información o influir en la toma de decisiones de forma deshonesta.</li>
    <li>Proporcionar información actualizada y no engañosa en el momento de inscribirse en el Registro y de mantenerla actualizada, y garantizar que la que se suministre en cumplimiento de lo dispuesto en la ordenanza es correcta y fidedigna.</li>
    <li>No incitar a los titulares de los órganos directivos a incumplir lo dispuesto en el capítulo VI de la ordenanza.</li>
  </ol>
  <p>La inscripción supondrá, asimismo, el compromiso de no efectuar regalos no permitidos según lo dispuesto en el Acuerdo de 5 de noviembre de 2015 de la Junta de Gobierno de la Ciudad de Madrid por el que se establece el régimen de regalos que reciban el Alcalde, los Miembros de la Junta de Gobierno, los Concejales con responsabilidades de gobierno, los Concejales-Presidentes de los Distritos, los titulares de los órganos directivos y los empleados públicos del Ayuntamiento de Madrid y sus organismos autónomos.
  <p>La inexactitud, falsedad u omisión, de carácter esencial, de cualquier dato o información que se incorpore a la declaración responsable o la no presentación ante el Ayuntamiento de la documentación que sea en su caso requerida para acreditar el cumplimiento de lo declarado, determinará la baja en el registro, la pérdida de los incentivos e imposibilidad de mantener reuniones con concejales, titulares de los órganos directivos del Ayuntamiento de Madrid y sus organismos autónomos y el personal eventual.
  <p>Por otra parte, sobre los concejales, titulares de órganos directivos y personal eventual recae el deber de no celebrar reuniones ni encuentros con personas no inscritas en el Registro de Lobbies (artículos 39 y 40.2 de la ordenanza). El incumplimiento de este deber puede dar lugar a la adopción por parte de la Comisión de Seguimiento de la Ordenanza de Transparencia de alguna de las medidas que contemplan los artículos 41 y 42:
  <ol type="a">
    <li>Solicitar informe para aclarar las circunstancias del presunto incumplimiento.</li>
    <li>Elaborar una recomendación que se publicará en el Boletín Oficial del Ayuntamiento de Madrid y en el Portal de Transparencia, y que podrá identificar a las persona sujeta a este deber.</li>
    <li>
      Proponer a la Junta de Gobierno:
      <ol type="1">
        <li>Un apercibimiento, en caso de que el incumplimiento haya generado un daño leve al interés público.</li>
        <li>El cese, en el caso de que el incumplimiento haya generado un daño grave al interés público. En este supuesto, la medida solo podrá tomarse a propuesta del titular del área de gobierno que corresponda en cada caso.</li>
      </ol>
    </li>
  </ol>
  <p>Cada una de estas medidas se podrá aplicar atendiendo a la naturaleza del sujeto sobre el que recaiga (en caso de los concejales, no se podrá proponer su cese, por ejemplo).
  <p>Para más información, puedes consultar las normas y acuerdos que conforman el marco jurídico del Registro de Lobbies en la Ciudad de Madrid:
  <ul>
    <li><a href="https://sede.madrid.es/sites/v/index.jsp?vgnextfmt=default&vgnextchannel=6b3d814231ede410VgnVCM1000000b205a0aRCRD&vgnextoid=3eabe8e52c796510VgnVCM1000001d4a900aRCRD&titulo1=7&target=texto">Título VI de la Ordenanza de Transparencia de la Ciudad de Madrid y artículos 40.2, 41 y 42.</a></li>
    <li><a href="https://transparencia.madrid.es/FWProjects/transparencia/RelacionCiudadania/RegistroLobbies/Acuerdo_Pleno_28_06_2017.pdf">Acuerdo de 28 de junio de 2017 del Pleno del Ayuntamiento de Madrid por el que se establecen las líneas básicas del Registro de lobbies regulado en la Ordenanza de Transparencia de la Ciudad de Madrid.</a></li>
    <li><a href="https://sede.madrid.es/FrameWork/generacionPDF/boam8060_2790.pdf?numeroPublicacion=8060&idSeccion=f3b7b1a5e9470610VgnVCM1000001d4a900aRCRD&nombreFichero=boam8060_2790&cacheKey=60&guid=d3899999a6370610VgnVCM1000001d4a900aRCRD&csv=true">Acuerdo de 20 de diciembre de 2017 de la Junta de Gobierno de la Ciudad de Madrid por el que se aprueban los criterios de funcionamiento del Registro de lobbies regulado en la Ordenanza de Transparencia de la Ciudad de Madrid.</a></li>
  </ul>
</div>

app/views/static_pages/websitemap.html.erb
<div class="small-12 column">

  <% content_for :description do %>
    <%=t 'websitemap.content'%>
  <% end %>

  <p><a href="/"><%= t "websitemap.cover_page" %></a></p>
  <p><a href="/visitors"><%= t "websitemap.agendas" %></a></p>
  <p><%= link_to t("websitemap.registration_lobbies"), registration_lobbies_path %></p>
    <ul>
    <li><%= link_to t("websitemap.search_lobbies"), organizations_path %></li>
    <li><%= link_to t("websitemap.update_lobbies"), edit_organization_path %></li>
    <li><%= link_to t("websitemap.rules_lobbies"), "/code_of_conduct"%></li>
    <li><%= link_to t("websitemap.faq"), faq_path %></li>
    <li><%= link_to t("websitemap.stadistics"), statistics_path %></li>
    <li><%= link_to t("websitemap.mailbox"), new_infringement_email_path %></li>
    </ul>
  <p><%= link_to t("websitemap.regulations_lobbies"), 'https://transparencia.madrid.es/portales/transparencia/es/Informacion-juridica/Huella-normativa?vgnextfmt=default&vgnextchannel=4099508929a56510VgnVCM1000008a4a900aRCRD', target: 'blank', accesskey: 3 %></p>
</div>