config/routes.rb
Rails.application.routes.draw do

  resources :range_subventions
  resources :addresses
  resources :notification_effects
  get 'calendar/index'

  # Public resources
  root to: 'homepage#index', format: false
  
  
  get 'authorize' => 'auth#gettoken'
  get '/redirect', to: 'events#redirect', as: 'redirect'
  get '/callback', to: 'events#callback', as: 'callback'
  get '/calendars', to: 'events#calendars', as: 'calendars'

  get '/lang/:lang', to: 'application#change_language', as: 'change_language'
  get '/show/:id', to: 'visitors#show', as: 'show'
  get '/update_holders', to: 'visitors#update_holders', as: 'update_holders'
  get '/inicio.do', to: 'uweb_access#uweb_sign_in'
  get '/agenda/:holder/:full_name', to: 'visitors#agenda', as: 'agenda'

  get '/faq', to: 'questions#index', as: 'faq'
  get '/websitemap', to: 'static_pages#websitemap', as: 'websitemap'

  post '/ws/agends', to: 'ws/agends#generic'
  post '/ws/agends/:personal_code', to: 'ws/agends#holder'

  resources :statistics, only: [:index]
  resources :statistics do
    get :lobbies, on: :collection
  end

  get '/code_of_conduct', to: 'static_pages#code_of_conduct', as: 'code_of_conduct'
  get '/accessibility', to: 'static_pages#accessibility', as: 'accessibility'

  get '/homepage', to: 'homepage#index', as: 'homepage'
  get 'registration_lobbies/index'
  get '/registration_lobbies', to: 'registration_lobbies#index', as: 'registration_lobbies'
  get '/visitors', to: 'visitors#index', as: 'visitors'
  get '/export_events', to: 'visitors#export_events', as: 'visitors_export_events'

  # Admin
  get "/admin", to: 'events#index', as: 'admin'
  
  #namespace :api do
    wash_out :servicio_integracion_bareg
  #end
  

  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :events do
    get :download, on: :collection
    get :clone, on: :member
    get :export_outlook, on: :member
    get :get_calendars, on: :member
  end
  
 
  resources :areas
  resources :activities
  resources :infringement_emails, only: [:new, :create]
  resources :holders do 
    get :active, on: :collection
    get :mail, on: :member
    post :send_mail, on: :member
    get :export_all, on: :collection
    get :search, on: :collection
  end


  namespace :admin do
    resources :notifications, except: [:index, :new, :create, :destroy] do 
      get :active, on: :collection
      get :historic, on: :collection
      get :pre_recover, on: :member
      post :recover, on: :member
      get :pre_canceled, on: :member
      post :canceled, on: :member
      get :permited, on: :member
      get :manually_permited, on: :member
      get :recover_origin, on: :member
      post :update_notification, on: :member
    end
    resources :exports
    resources :parametrizations, only: [:index] do
      post :change_view, on: :collection
      post :length_event_description, on: :collection
      post :send_email, on: :collection
      post :update_configure_text, on: :member
      get :download_log
    end
    resources :manage_emails
    resources :users do 
      get :revert, on: :member
      get :assign_holder, on: :collection
      get :export_manages, on: :collection
      get :uweb, on: :collection
    end
    get 'passwords/edit', to: 'passwords#edit', as: 'edit_password'
    match 'passwords/update', to: 'passwords#update', as: 'update_password', via: [:patch, :put]
    resources :organizations do
      resources :agents
      resources :organization_interests, only: [:index]
      match 'interests_update', to: 'organization_interests#update', as: 'interests_update', via: [:patch, :put]
    end
    resources :organizations_links
    resources :questions
    post 'order_questions', to: 'questions#order', as: 'order_questions'

    resources :newsletters do
      member do
        post :deliver
      end
      get :users, on: :collection
    end
  end

  resources :positions do
    get :autocomplete_position_title, :on => :collection
  end
  get '/organizations/edit', to: 'organizations#edit', as: 'edit_organization'
  get '/organizations/destroy', to: 'organizations#destroy', as: 'destroy_organization'
  get '/organizations/new', to: 'organizations#new', as: 'new_organization'
  resources :organizations, except: [:new, :edit, :destroy] do
    get :autocomplete_organization_name, :on => :collection
    resources :represented_entities, only: :index, format: :json
    resources :agents, only: :index, format: :json
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get '*path' => redirect { |p, req| req.flash[:alert] = "No se encuentra la ruta especificada"; '/' } unless Rails.env.development?

end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  self.primary_key = :id
  
  def readonly?
    true
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController  
  before_filter :set_holder, only: [:index, :agenda]

  def index
    get_events_array
    begin
        respond_to do |format|
          format.csv { stream_csv_report.delay  }
          format.html
          format.atom
        end
    rescue
    end
  rescue => e
    begin
      Rails.logger.error("COD-00001: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def show
    @event = Event.friendly.find(params[:id])
  rescue => e
    begin
      Rails.logger.error("COD-00002: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
    redirect_to visitors_path, alert: "No se puede acceder a esta información"
  end

  def agenda
    if @holder.blank?
      redirect_to visitors_path, alert: t('activerecord.models.holder.not_found')
    else
      index
      render :index
    end
  rescue => e
    begin
      Rails.logger.error("COD-00003: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def update_holders
    @holders =  HoldersAppointment.all.order(last_name: :asc)
  rescue => e
    begin
      Rails.logger.error("COD-00004: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  private

 
  def stream_csv_report
    stream_file("Agendas", "csv") do |stream|
      Event.stream_query_rows(@unpaginated_events, request.base_url) do |row_from_db|
        stream.write row_from_db
      end
    end
  end

  def set_holder
    @holder = Holder.where(id: params[:holder]).first if !params[:holder].blank?
    @holders = HoldersAppointment.all.order(last_name: :asc)
  end

  def get_events_array  
    events = Event.where("events.status in (1,2) AND (cast(events.published_at as date) <= cast(? as date) OR events.published_at IS NULL)", ActiveRecord::Base::sanitize(Time.zone.now.strftime("%Y-%m-%d").to_s)).select(:title,:id,:slug,:position_id,:scheduled).order(scheduled: :desc) 
    if !DataPreference.find_by(title: 'limit_events').try(:content_data).blank? && (current_user.blank? || !current_user.blank? && !current_user.admin? || !DataPreference.find_by(title: 'show_admin_limit').try(:content_data).blank? && DataPreference.find_by(title: 'show_admin_limit').try(:content_data) == "2")
      events = events.where("cast(events.scheduled as date) >= cast(? as date)", ActiveRecord::Base::sanitize(Time.zone.parse(DataPreference.find_by(title: 'limit_events').content_data)))
    end

    if !params[:holder].blank? 
      events = events.where("events.position_id in (?) OR events.id in (?)", Position.where(holder_id: params[:holder].to_i).select(:id),
        Participant.joins(:position).where("positions.holder_id = '?'", params[:holder].to_i).select(:event_id).select(:event_id))       
    end    

    if !params[:advanced_search].blank?  && params[:advanced_search] == 'advanced'
      events = events.where(lobby_activity: true) if !params[:lobby_activity].blank?

      if !params[:keyword].to_s.strip.blank?
        aux_key=params[:keyword].to_s.strip
        events = events.where("
          TRANSLATE(UPPER(events.title),'ÁÉÍÓÚ','AEIOU') LIKE TRANSLATE(UPPER(?),'ÁÉÍÓÚ','AEIOU') 
          OR TRANSLATE(UPPER(events.description),'ÁÉÍÓÚ','AEIOU') LIKE TRANSLATE(UPPER(?),'ÁÉÍÓÚ','AEIOU')
          OR events.position_id in (?)
          OR events.position_id in (?)
          OR events.position_id in (?)
          OR events.id in (?)
          OR events.id in (?)
        ", "%#{aux_key}%", 
        "%#{aux_key}%", 
        Position.where("TRANSLATE(UPPER(positions.title),'ÁÉÍÓÚ','AEIOU') LIKE TRANSLATE(UPPER(?),'ÁÉÍÓÚ','AEIOU')","%#{aux_key}%").select(:id).uniq, 
        Position.joins(:holder).where("TRANSLATE(UPPER(CONCAT(holders.first_name, ' ', holders.last_name)),'ÁÉÍÓÚ','AEIOU') LIKE TRANSLATE(UPPER(?),'ÁÉÍÓÚ','AEIOU')","%#{aux_key}%").select(:id), 
        Position.joins(:area).where("TRANSLATE(UPPER(areas.title),'ÁÉÍÓÚ','AEIOU') LIKE TRANSLATE(UPPER(?),'ÁÉÍÓÚ','AEIOU')","%#{aux_key}%").select(:id), 
        Participant.joins(:position => [:holder]).where("TRANSLATE(UPPER(CONCAT(holders.first_name, ' ', holders.last_name)),'ÁÉÍÓÚ','AEIOU') LIKE TRANSLATE(UPPER(?),'ÁÉÍÓÚ','AEIOU')","%#{aux_key}%").select(:event_id), 
        Attendee.where("TRANSLATE(UPPER(attendees.name),'ÁÉÍÓÚ','AEIOU') LIKE TRANSLATE(UPPER(?),'ÁÉÍÓÚ','AEIOU')","%#{aux_key}%").select(:event_id))
      end

      if !params[:from].blank? && !params[:to].blank?
        events = events.where("CAST(events.scheduled as date) BETWEEN CAST(? as date) AND  CAST(? as date)", Time.zone.parse(params[:from]), Time.zone.parse(params[:to]))
      elsif !params[:from].blank?
        events = events.where("CAST(events.scheduled as date) >= CAST(? as date) ", Time.zone.parse(params[:from]))
      elsif !params[:to].blank?
        events = events.where("CAST(events.scheduled as date) <= CAST(? as date) ", Time.zone.parse(params[:to]))
      end
    elsif params[:advanced_search].blank? || params[:advanced_search] == 'calendar'
      @date_start = nil
      @date_end = nil
      if params[:select].blank?
        begin
          @current_date_calendar = params[:set_date].blank? ? Time.zone.now.to_date : Time.zone.parse(params[:set_date]).to_date
        rescue
          @current_date_calendar = Time.zone.now.to_date
        end
        @date_start = @current_date_calendar
      else
        begin
          @current_date_calendar=Date.new(params[:select][:year].to_i, params[:select][:month].to_i, params[:select][:day].to_i)
        rescue
          @current_date_calendar = Date.new(params[:select][:year].to_i, params[:select][:month].to_i, 1)
        end
        if params[:tab_calendar].blank? 
          @date_start = @current_date_calendar
        elsif params[:tab_calendar] == "today"
          @current_date_calendar =  Time.zone.now.to_date
          @date_start = @current_date_calendar    
        elsif params[:tab_calendar] == "week"
          @date_start = @current_date_calendar - (@current_date_calendar.wday - 1)
          @date_end = @current_date_calendar + (7 - @current_date_calendar.wday) 
        elsif params[:tab_calendar] == "month"
          @date_start = Date.new(params[:select][:year].to_i, params[:select][:month].to_i, 1)
          @date_end = Date.new(params[:select][:year].to_i, params[:select][:month].to_i, -1)         
        end
      end
    
      if !@date_start.blank? && !@date_end.blank?
        events = events.where("CAST(events.scheduled as date) BETWEEN CAST(? as date) AND  CAST(? as date)", @date_start, @date_end)
      elsif !@date_start.blank?
        events = events.where("CAST(events.scheduled as date) BETWEEN CAST(? as date) AND  CAST(? as date)", @date_start, @date_start)
      end
    end
    @unpaginated_events = events
    @paginated_events = events.page(params[:page] || 1).per(100) 
  end  
  
end

app/views/visitors/_event.html.erb
<div class="small-12 columns mb20">
  <article id="<%= event.id.to_i%>" class="post event">
    <h2 class="post__title"><%= link_to event.title, show_path(event.slug) %></h2>
    <p><strong>
      <%= show_agenda_link_array(event.holder_name.try(:custom_titleize), event.position.try(:holder_id)) %> ·
      <%= event.position.try(:title).try(:custom_titleize) %> ·
      <%= event.position.try(:area).try(:title).try(:custom_titleize) %>
    </strong></p>
    <p><%= I18n.l event.scheduled, format: :complete if !event.scheduled.blank? %></p>
  </article>
</div>

app/views/visitors/_export_data.html.erb
<div class="small-12 large-8 large-ofsset-1 columns mb40">  
  <div class="small-12 columns tools">
    <div class="mb20">
      <%= t('main.get_updates')%><a id= "atom_link" href="<%= current_url(format: :atom)%>"><span class="icon icon__feed"></span> feed</a>
      <%= export_link(current_url(format: :csv)) %>
      <%= pdf_visitors_link(current_url({})) %>
    </div>
  </div>
</div>

app/views/visitors/_form.html.erb
<p class="mb40"><%= t('main.form.title')%></p>
<%= form_tag visitors_path, method: :get, class: 'advanced_form' do %>
  <%= hidden_field_tag :advanced_search, params[:advanced_search] %>
  <div class="mb20">
    <%= label_tag :keyword, t('main.form.main_keyword'), class: 'title-s' %>
    <%= text_field_tag :keyword, params[:keyword], placeholder: t('main.form.keyword') %>
  </div>
  <div class="mb20">
    <div class="small-12 columns" style="display: contents;">
        <%= label_tag :holder, t('main.form.holder'), class: 'title-s' %>
        <%= select_tag :holder, options_for_select(@holders.try{|x| x.map{|holder| [holder.full_name_comma_with_active, holder.id]}},params[:holder]),prompt: t('main.form.any'), class: 'dropdown js-example-basic-multiple' %>
    </div>
  </div>
  <b><%= t('main.form.date') %></b>
  <div class="mb20">
    <div class="small-6 columns" style="padding:5px">
      <%= label_tag :from, t('main.form.fromdate'), class: 'title-s' %>
      <%= date_field_tag :from,params[:from], class: 'title-s'%>
    </div>
    <div class="small-6 columns" style="padding:5px">
      <%= label_tag :to, t('main.form.todate'), class: 'title-s' %>
      <%= date_field_tag :to,params[:to] , class: 'title-s'%>
    </div>
  </div>

  <div class="small-12 left mb20">
    <%= check_box_tag(:lobby_activity, value = "1", checked = check_filter_lobby_activity , id: "lobby_activity")%>
    <%= label_tag(:lobby_activity, t("backend.lobby_activity")) %>
  </div>

  <div class="mb20 text-center">
    <%= submit_tag t('main.form.search'), class: 'button', name: nil %>
    <%= link_to t('main.form.reset'), visitors_path(advanced_search: "advanced"), class: 'button secondary'%>
  </div>

   <div class="mb20 text-center">
      <%= link_to t('main.form.calendar_search'), visitors_path(advanced_search: "calendar"), class: 'button'%>
   </div>
<% end %>

app/views/visitors/_list_events.html.erb
<div class="small-12 medium-6 large-8 large-ofsset-1 columns ml40">    
    <div id="list" style= "visibility:inherit; display:block;">
        <%if !@paginated_events.blank?%>
            <%= render "paginate_events", export: true%>
            <% @paginated_events.each do |event|%>
                <%= render "visitors/event", event: event %>
            <% end %>
            <%= render "paginate_events"%>
        <%else%>
            <% if !@date_start.blank? && (params[:advanced_search].blank? || params[:advanced_search] == 'calendar') %>
                <p>No hay eventos en el listado <%= " en el periodo: #{@date_start.strftime("%d/%m/%Y")} #{"- #{@date_end.strftime("%d/%m/%Y")}" if !@date_end.blank?}" %></p>
            <% else %>
                <p>No hay eventos en el listado</p>
            <% end %>
        <%end%>
    </div>
</div> 

app/views/visitors/_month_calendar.html.erb
<% if params[:advanced_search].blank? || params[:advanced_search] == 'calendar' %>
    <%= form_tag current_path_with_query_params(params), method: :get, class: 'dates_form' do %>
        <%= hidden_field_tag :tab_calendar, params[:tab_calendar] %>
        <%= hidden_field_tag :set_date, params[:set_date] %>
        <div class="mb20">
            <div class="small-12 columns calendar_columns">
                <div class="small-4 columns calendar_columns">
                    <%=label_tag :select_day, "Día", class: "sr-only" %>
                    <%= select_day(@current_date_calendar,{prefix: :select},{onchange: "send_form()"})%>
                </div>
                <div class="small-4 columns calendar_columns">
                    <%=label_tag :select_month, "Mes", class: "sr-only" %>
                    <%= select_month(@current_date_calendar,{prefix: :select},{onchange: 'send_form()'})%>
                </div>
                <div class="small-4 columns calendar_columns">
                    <%=label_tag :select_year, "Año", class: "sr-only" %>
                    <%= select_year(@current_date_calendar, {prefix: :select,start_year: 2005},{onchange: 'send_form()'})%>
                </div>
            </div>           
            <div class="small-12 columns" style="padding: 0px;overflow-x:auto;">   
                <table class="table table-striped" style="width: 100%">
                    <thead><tr><%=get_week_first_monday%></tr></thead>
                    <tbody><%=get_days_month_range(@current_date_calendar, @unpaginated_events, params)%></tbody>
                </table>
            </div>
            <div class="small-4 columns" style="padding: 3px;">
                <%=link_to t("calendar.week"), set_tab_calendar(params, "week",@current_date_calendar), class: "button #{"secondary" if params[:tab_calendar].to_s!= "week"} calendar_buttons"%>
            </div>
            <div class="small-4 columns" style="padding: 3px;">
                <%=link_to t("calendar.month"), set_tab_calendar(params, "month",@current_date_calendar), class: "button #{"secondary" if params[:tab_calendar].to_s!= "month"} calendar_buttons"%>
            </div>
            <div class="small-4 columns" style="padding: 3px;">
                <%= link_to t("calendar.now"), set_now_calendar(params), class: "button #{"secondary" if (!@current_date_calendar.blank? &&  @current_date_calendar != Date.today||!params[:set_date].blank? && params[:set_date].to_date != Date.today || !params[:tab_calendar].blank? && params[:tab_calendar] != 'today') } calendar_buttons" %>
            </div>
        </div>
        <div class="mb20" >
            <div class="small-12 columns">
                <%= label_tag :holder, t('main.form.holder'), class: 'title-s' %>
                <%= select_tag :holder, options_for_select(@holders.try{|x| x.map{|holder| [holder.full_name_comma_with_active, holder.id]}},params[:holder]),prompt: t('main.form.any'), class: 'dropdown js-example-basic-multiple', style: "width: 100%", onchange: 'this.form.submit()' %>
            </div>
        </div>
        <div class="mb20 text-center" >
            <%= link_to t('main.form.reset_calendar'), visitors_path(advanced_search: "calendar"), class: 'button secondary', style:'margin-top: 2rem;'%>
        </div>
        <div class="mb20 text-center">
            <%= link_to t('main.form.advanced_search'), visitors_path(advanced_search: "advanced"), class: 'button'%>
        </div>
    <%end%>
<% else %>
    <%= render 'form' %>
<% end %>

app/views/visitors/_paginate_events.html.erb
<% export ||= false%>
<div class="small-<%=export ? '10' : '12'%> columns mb20">
    <% if !@date_start.blank? && (params[:advanced_search].blank? || params[:advanced_search] == 'calendar') %>
        <%= page_entries_info @paginated_events %> <%= " en el periodo: #{@date_start.strftime("%d/%m/%Y")} #{"- #{@date_end.strftime("%d/%m/%Y")}" if !@date_end.blank?}" %>
    <% else %>
        <%= page_entries_info @paginated_events %>
    <% end %>
    <%= paginate @paginated_events, params: {:select => {:day => @current_date_calendar.try(:day), :month => @current_date_calendar.try(:month), :year => @current_date_calendar.try(:year) }} %>
</div>
<%if export%>
    <div class="small-2 columns mb20">
        <%= export_link(current_url(format: :csv)) %>
    </div>
<%end%>

app/views/visitors/index.csv.erb
<%=
  exporter = EventsExporter.new

  CSV.generate(col_sep: ';', encoding: 'ISO-8859-1') do |csv|
    csv << exporter.windows_headers

    if !@events.blank?
      @events.each do |event|
        csv << exporter.windows_event_row(event)
      end
    end
  end.html_safe
%>

app/views/visitors/index.html.erb
<% content_for(:body_class) { 'visit-visitors-events' } %>

<div class="row">
  <div class="small-12 medium-6 large-4 columns">
    <%= render 'month_calendar' %>
  </div>
  <%= render 'list_events' %>
</div>

app/views/visitors/show.html.erb
<% content_for :title, t('site_title') + @event.title %>


<div class="row">
  <div class="small-12 columns">
    <%= link_to t('backend.back'), :back , class: "button tiny radius" %>
  </div>
  <div class="small-12 columns">
    <h2 class="post__title-big"><%= @event.title %></h2>
    <span><%= I18n.l @event.scheduled, format: :complete if @event.scheduled %></span>
  </div>
</div>

<div class="row">
  <br />
  <div class="small-12  event_actions columns">
    <%= social_share_button_tag(@event.title, url:  agenda_url( @event.position.holder_id,@event.holder_name.parameterize)) %>
  </div>
</div>

<div class="small-12 columns">
  <hr />
  <ul class="accordion" role = "tablist">

      <li class="accordion-navigation active">
        <div class="accordion-title">
          <strong><%= t('show.holder')%></strong>
          <span class="accordion-icon"></span>
        </div>
        <div class="content active">
          <strong><%= show_agenda_link(@event.position.holder) %></strong>
          <p><%= @event.position.title.custom_titleize %></p>
          <p><%= @event.position.area.title.custom_titleize %></p>
        </div>
      </li>

      <li class="accordion-navigation active">
        <div class="accordion-title">
          <strong><%= t('show.participants')%></strong>
        </div>
        <div class="content active">
          <%if @event.multi_attendees.to_s != 'true'%>
            <% @event.attendees.each do |attendee|%>
              <p>
                <strong><%= attendee.name %></strong>
              </p>
              <p><%= attendee.position %></p>
              <p><%= attendee.company %></p>
              <br />
            <% end %>
            <% @event.participants.each do |participant|%>
            <p>
              <strong><%= show_agenda_link(participant.position.holder) %></strong>
            </p>
            <p><%= participant.position.title.custom_titleize %></p>
            <p><%= participant.position.area.title.custom_titleize %></p>
            <br />
            <% end %>
          <%else%>
            <%=t('backend.multi_attendees')%>
          <%end%>
        </div>
      </li>

      <li class="accordion-navigation active">
        <div class="accordion-title">
          <strong><%= t('show.location')%></strong>
        </div>
        <div class="content active">
          <p><%= @event.location %></p>
        </div>
      </li>

      <li class="accordion-navigation active">
        <div class="accordion-title">
          <strong><%= t('show.description')%></strong>
        </div>
        <div class="content active">
          <%= @event.description.html_safe if @event.description.present? %>
        </div>
      </li>

      <% if @event.attachments.count > 0 %>
        <li class="accordion-navigation active">
          <div class="accordion-title">
            <strong><%= t('show.documentation')%></strong>
          </div>
          <div class="content active">
            <% @event.attachments.each do |attachment| %>
              <% unless attachment.public == false %>
                <p><%= link_to attachment.title, attachment.file.url,target: :blank %></p>
                <%= attachment.description.html_safe if attachment.description.present? %>
              <% end %>
            <% end %>
          </div>
        </li>
      <% end %>
      <% if @event.lobby_activity%>
        <% @event.events_organizations.each do |event_organization| %>
          <% organization = event_organization.organization %>
          <%if !organization.blank? && organization.entity_type.to_s == "lobby" %>
            <li class="accordion-navigation active">
              <div class="accordion-title">
                <strong>Información del lobby:</strong>
              </div>
              <div class="content active">
                <strong>Nombre:</strong>
                <br />
                <%= link_to organization.fullname, organization_path(organization) %>

                <br />
                <br />
                <strong>Agentes:</strong>
                <br />
                <% event_organization.event_agents.each do |agent| %>
                  <p><%= agent.name %></p>
                <% end %>
                <br />
                <strong>Empresas/personas físicas representadas:</strong>
                <br />
                <% event_organization.event_represented_entities.each do |represented_entity| %>
                  <p><%= represented_entity.name %></p>
                <% end %>
              </div>
            </li>
          <%else%>
            <li class="accordion-navigation active">
                <div class="accordion-title">
                  <strong><%=t('show.lobby')%></strong>
                </div>
                <div class="content active">
                  <strong>Nombre:</strong>
                  <br />
                  <%= link_to organization.fullname, organization_path(organization) %>
                </div>
            </li>
          <% end %>
        <% end %>
      <% end %>
    </ul>
</div>

app/views/visitors/update_areas.js.erb
$("#child_area").empty().append("<%= escape_javascript(render(partial: @areas)) %>");
$("#child_area").prepend("<option value=''><%= t('main.form.any')%></option>").val('');

app/views/visitors/update_holders.js.erb
$("#holder").empty().append("<%= escape_javascript(render(partial: @holders)) %>")
$("#holder").prepend("<option value=''><%= t('main.form.any')%></option>").val('');