config/routes.rb
Rails.application.routes.draw do

  resources :range_subventions
  resources :addresses
  resources :notification_effects
  get 'calendar/index'

  # Public resources
  root to: 'homepage#index', format: false
  
  
  get 'authorize' => 'auth#gettoken'
  get '/redirect', to: 'events#redirect', as: 'redirect'
  get '/callback', to: 'events#callback', as: 'callback'
  get '/calendars', to: 'events#calendars', as: 'calendars'

  get '/lang/:lang', to: 'application#change_language', as: 'change_language'
  get '/show/:id', to: 'visitors#show', as: 'show'
  get '/update_holders', to: 'visitors#update_holders', as: 'update_holders'
  get '/inicio.do', to: 'uweb_access#uweb_sign_in'
  get '/agenda/:holder/:full_name', to: 'visitors#agenda', as: 'agenda'

  get '/faq', to: 'questions#index', as: 'faq'
  get '/websitemap', to: 'static_pages#websitemap', as: 'websitemap'

  post '/ws/agends', to: 'ws/agends#generic'
  post '/ws/agends/:personal_code', to: 'ws/agends#holder'

  resources :statistics, only: [:index]
  resources :statistics do
    get :lobbies, on: :collection
  end

  get '/code_of_conduct', to: 'static_pages#code_of_conduct', as: 'code_of_conduct'
  get '/accessibility', to: 'static_pages#accessibility', as: 'accessibility'

  get '/homepage', to: 'homepage#index', as: 'homepage'
  get 'registration_lobbies/index'
  get '/registration_lobbies', to: 'registration_lobbies#index', as: 'registration_lobbies'
  get '/visitors', to: 'visitors#index', as: 'visitors'
  get '/export_events', to: 'visitors#export_events', as: 'visitors_export_events'

  # Admin
  get "/admin", to: 'events#index', as: 'admin'
  
  #namespace :api do
    wash_out :servicio_integracion_bareg
  #end
  

  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :events do
    get :download, on: :collection
    get :clone, on: :member
    get :export_outlook, on: :member
    get :get_calendars, on: :member
  end
  
 
  resources :areas
  resources :activities
  resources :infringement_emails, only: [:new, :create]
  resources :holders do 
    get :active, on: :collection
    get :mail, on: :member
    post :send_mail, on: :member
    get :export_all, on: :collection
    get :search, on: :collection
  end


  namespace :admin do
    resources :notifications, except: [:index, :new, :create, :destroy] do 
      get :active, on: :collection
      get :historic, on: :collection
      get :pre_recover, on: :member
      post :recover, on: :member
      get :pre_canceled, on: :member
      post :canceled, on: :member
      get :permited, on: :member
      get :manually_permited, on: :member
      get :recover_origin, on: :member
      post :update_notification, on: :member
    end
    resources :exports
    resources :parametrizations, only: [:index] do
      post :change_view, on: :collection
      post :length_event_description, on: :collection
      post :send_email, on: :collection
      post :update_configure_text, on: :member
      get :download_log
    end
    resources :manage_emails
    resources :users do 
      get :revert, on: :member
      get :assign_holder, on: :collection
      get :export_manages, on: :collection
      get :uweb, on: :collection
    end
    get 'passwords/edit', to: 'passwords#edit', as: 'edit_password'
    match 'passwords/update', to: 'passwords#update', as: 'update_password', via: [:patch, :put]
    resources :organizations do
      resources :agents
      resources :organization_interests, only: [:index]
      match 'interests_update', to: 'organization_interests#update', as: 'interests_update', via: [:patch, :put]
    end
    resources :organizations_links
    resources :questions
    post 'order_questions', to: 'questions#order', as: 'order_questions'

    resources :newsletters do
      member do
        post :deliver
      end
      get :users, on: :collection
    end
  end

  resources :positions do
    get :autocomplete_position_title, :on => :collection
  end
  get '/organizations/edit', to: 'organizations#edit', as: 'edit_organization'
  get '/organizations/destroy', to: 'organizations#destroy', as: 'destroy_organization'
  get '/organizations/new', to: 'organizations#new', as: 'new_organization'
  resources :organizations, except: [:new, :edit, :destroy] do
    get :autocomplete_organization_name, :on => :collection
    resources :represented_entities, only: :index, format: :json
    resources :agents, only: :index, format: :json
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get '*path' => redirect { |p, req| req.flash[:alert] = "No se encuentra la ruta especificada"; '/' } unless Rails.env.development?

end

app/helpers/admin/organizations_helper.rb
module Admin
  module OrganizationsHelper
    def form_new_organization?
      params[:controller] == "admin/organizations" &&
        (params[:action] == "new" || params[:action] == "create")
    rescue => e
      begin
        Rails.logger.error("COD-00001: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def category_name(id)
      return if id.blank?
      Category.find(id).try(:name)
    rescue => e
      begin
        Rails.logger.error("COD-00002: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def address_number_types
      ["Num", "Km", "S/N"].sort.map { |rl| [rl, rl] }
    rescue => e
      begin
        Rails.logger.error("COD-00003: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def option_identifier_types
      ["DNI/NIF", "NIF", "NIE", "Pasaporte"].sort.map { |rl| [rl, rl] }
    rescue => e
      begin
        Rails.logger.error("COD-00004: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def show_partial?(partial)
      params[:show] ? params[:show] == partial && current_user.lobby? : false
    rescue => e
      begin
        Rails.logger.error("COD-00005: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def organization_attachments_download_dropdown_id(organization)
      "organization_#{organization.try(:id)}_attachments_dropdown"
    rescue => e
      begin
        Rails.logger.error("COD-00006: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def options_for_registered_lobby
      RegisteredLobby.where("name is not null AND name !='' ").order("CASE WHEN name='Ninguno' THEN 1 WHEN name='Otro' THEN 3 ELSE 2 END, name").map { |rl| [rl.name, rl.id] }.uniq
    rescue => e
      begin
        Rails.logger.error("COD-00007: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def options_for_provinces
      Province.where("name is not null AND name !='' ").order(name: :asc).map { |rl| [rl.name, rl.name] }.uniq
    rescue => e
      begin
        Rails.logger.error("COD-00008: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def options_for_countries
      Country.where("name is not null AND name !='' ").order(name: :asc).map { |rl| [rl.name, rl.name] }.uniq
    rescue => e
      begin
        Rails.logger.error("COD-00009: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def options_for_road_types
      RoadType.where("name is not null AND name !='' ").order(name: :asc).map { |rl| [rl.name, rl.name] }.uniq
    rescue => e
      begin
        Rails.logger.error("COD-00010: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def permit_category_with_money(model = nil)
      return false if model.blank?
      model.category.category.name.to_s == "Entidad con ánimo de lucro"
    rescue => e
      begin
        Rails.logger.error("COD-00011: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
      false
    end

    def permit_category_without_money(model = nil)
      return false if model.blank?
      model.category.category.name.to_s == "Entidad sin ánimo de lucro" && model.category.name.to_s != "Agrupaciones de personas que se conformen como plataformas, movimientos, foros o redes ciudadanas sin personalidad jurídica, incluso las constituidas circunstancialmente"
    rescue => e
      begin
        Rails.logger.error("COD-00012: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
      false
    end

  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper

  def status_type
    [[I18n.t("main.form.active"), 1],[I18n.t("main.form.inactive"), 3], [I18n.t("main.form.inavilited"), 2], [I18n.t("main.form.expired"), 4]]
  end

  def types_lobby
    [[I18n.t("main.form.next_expired"),1],[I18n.t("backend.search_active.foreign_lobby_activity"),2],[I18n.t("backend.search_active.own_lobby_activity"),3]]
  end

  def organizations_index_subtitle
    if params[:order] == '1' || params[:order] == '2' || params[:order] == '3'
      t "organizations.results_title"
    else
      t "organizations.subtitle.default"
    end
  rescue => e
    begin
      Rails.logger.error("COD-00001: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def organization_represented_entities_url_pattern(format)
    url = organization_represented_entities_url(organization_id: 999, format: format, protocol: protocol_for_urls)
    url.gsub('999', 'organization_id')
  rescue => e
    begin
      Rails.logger.error("COD-00002: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def organization_agents_url_pattern(format)
    url = organization_agents_url(organization_id: 999, format: format, protocol: protocol_for_urls)
    url.gsub('999', 'organization_id')
  rescue => e
    begin
      Rails.logger.error("COD-00003: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def organization_category_url_pattern
    url = organization_url(id: 999, format: :json, protocol: protocol_for_urls)
    url.gsub('999', 'organization_id')
  rescue => e
    begin
      Rails.logger.error("COD-00004: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def protocol_for_urls
    if Rails.env.development? || Rails.env.test?
      :http
    else
      :https
    end
  rescue => e
    begin
      Rails.logger.error("COD-00005: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def search_by_filter?
    (params[:interests].present? || params[:category].present? || params[:keyword].present?)
  rescue => e
    begin
      Rails.logger.error("COD-00006: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def organization_status(organization)
    if !organization.canceled_at.blank? && organization.canceled_at <= Time.zone.now
      '<span class="label alert">Baja </span>'.html_safe
    elsif !organization.set_expired_date.blank? && organization.set_expired_date < Time.zone.now
      '<span class="label alert">Caducado </span>'.html_safe
    elsif organization.canceled?
      '<span class="label alert">Baja </span>'.html_safe
    elsif organization.invalidated?
      if current_user.present? && current_user.admin?
        '<span class="label warning">Inhabilitado</span>'.html_safe
      else
        '<span class="label alert">Baja </span>'.html_safe
      end
    else
      '<span class="label success">Activo</span>'.html_safe
    end
  rescue => e
    begin
      Rails.logger.error("COD-00007: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def organization_expired?(organization)
    !(!organization.canceled_at.blank? && organization.canceled_at <= Time.zone.now) && (!organization.organization_status.blank? && organization.organization_status.code=='expired'  ||  !organization.set_expired_date.blank? && organization.set_expired_date < Time.zone.now)
  rescue 
    false
  end

  def organization_list_status(organization)
    if  !organization.organization_status.blank? && organization.organization_status.code=='inactive'  || !organization.canceled_at.blank? && organization.canceled_at <= Time.zone.now
      '<span class="label alert">Baja </span>'.html_safe
    elsif  !organization.organization_status.blank? && organization.organization_status.code=='expired'  || !organization.set_expired_date.blank? && organization.set_expired_date < Time.zone.now
      '<span class="label alert">Caducado </span>'.html_safe
    elsif !organization.organization_status.blank? && ['inactive', 'invalidated'].include?(organization.organization_status.code) || organization.canceled? || organization.invalidated?
      '<span class="label alert">Baja </span>'.html_safe
    end
  rescue => e
    begin
      Rails.logger.error("COD-00008: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def events_as_lobby_by(organization)
    organization.events.where(lobby_activity: true, status: 2).count
  rescue => e
    begin
      Rails.logger.error("COD-00009: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def organization_back_button
    if current_user.present? && !params[:admin].blank? && params[:admin].to_s == "true"
      admin_organizations_path
    else
      organizations_path
    end
  rescue => e
    begin
      Rails.logger.error("COD-00010: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def link_to_organizations_sorted_by(column)
    direction = set_direction(params[:direction])
    icon = set_sorting_icon(direction, column)

    translation = t("backend.#{column}")

    link_to(
      "#{translation} <span class='icon-sortable #{icon}'></span>".html_safe,
      admin_organizations_path(sort_by: column, direction: direction, params: params.except(:direction, :sort_by))
    )
  rescue => e
    begin
      Rails.logger.error("COD-00011: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def set_sorting_icon(direction, sort_by)
    if sort_by.to_s == params[:sort_by]
      if direction == "desc"
        "desc"
      else
        "asc"
      end
    else
      ""
    end
  rescue => e
    begin
      Rails.logger.error("COD-00012: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def set_direction(current_direction)
    current_direction == "desc" ? "asc" : "desc"
  rescue => e
    begin
      Rails.logger.error("COD-00013: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

end

app/views/admin/organizations/_address_show.html.erb
<%if !model.try(:address).blank?%>
    <div class="row">
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.country') %></strong></p>
            <p><%= model.address.try(:country).blank? ? "<br>".html_safe : model.address.try(:country) %></p>
        </div>
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.province') %></strong></p>
            <p><%=  model.address.try(:province).blank? ? "<br>".html_safe : model.address.try(:province) %></p>
        </div>
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.town') %></strong></p>
            <p><%=  model.address.try(:town).blank? ? "<br>".html_safe : model.address.try(:town) %></p>
        </div>
    </div>
    <div class="row">
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.address_type') %></strong></p>
            <p><%= model.address.try(:address_type).blank? ? "<br>".html_safe : model.address.try(:address_type) %></p>
        </div>
        <div class="small-12 medium-8 columns">
            <p><strong><%= t('backend.identifying_data.address') %></strong></p>
            <p><%= model.address.try(:address).blank? ? "<br>".html_safe :  model.address.try(:address) %></p>
        </div>
    </div>
    <div class="row">
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.address_number_type') %></strong></p>
            <p><%= model.address.try(:address_number_type).blank? ? "<br>".html_safe : model.address.try(:address_number_type) %></p>
        </div>
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.number') %></strong></p>
            <p><%=  model.address.try(:number).blank? ? "<br>".html_safe : model.address.try(:number) %></p>
        </div>
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.gateway') %></strong></p>
            <p><%=model.address.try(:gateway).blank? ? "<br>".html_safe : model.address.try(:gateway) %></p>
        </div>
    </div>
    <div class="row">
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.stairs') %></strong></p>
            <p><%= model.address.try(:stairs).blank? ? "<br>".html_safe : model.address.try(:stairs) %></p>
        </div>    
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.floor') %></strong></p>
            <p><%= model.address.try(:floor).blank? ? "<br>".html_safe : model.address.try(:floor) %></p>
        </div>
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.door') %></strong></p>
            <p><%= model.address.try(:door).blank? ? "<br>".html_safe : model.address.try(:door) %></p>
        </div>
    </div>
    <div class="row">
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.postal_code') %></strong></p>
            <p><%= model.address.try(:postal_code).blank? ? "<br>".html_safe :  model.address.try(:postal_code) %></p>
        </div>        
        <div class="small-12 medium-8 columns">
            <p><strong><%= t('backend.identifying_data.email') %></strong></p>
            <p><%= model.address.try(:email).blank? ? "<br>".html_safe : model.address.try(:email) %></p>
        </div>
    </div>
    <div class="row">
        <div class="small-12 medium-12 columns">
            <p><strong><%= t('backend.identifying_data.phones') %></strong></p>
            <p><%= model.address.try(:phones).blank? ? "<br>".html_safe : model.address.try(:phones) %></p>
        </div>           
    </div> 
<%end%>

app/views/admin/organizations/_address_show.pdf.erb
<div class="small-12 medium-4 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.address_type') %></strong>
        <%= model.address.address_type %>
    </p>
</div>
<div class="small-12 medium-8 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.address') %></strong>
        <%= model.address.address %>
    </p>
</div>
<div class="small-12 medium-4 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.number') %></strong>
        <%= model.address.number %>
    </p>
</div>
<div class="small-12 medium-4 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.gateway') %></strong>
        <%= model.address.gateway %>
    </p>
</div>
<div class="small-12 medium-4 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.stairs') %></strong>
        <%= model.address.stairs %>
    </p>
</div>
<div class="small-12 medium-4 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.floor') %></strong>
        <%= model.address.floor %>
    </p>
</div>
<div class="small-12 medium-4 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.door') %></strong>
        <%= model.address.door %>
    </p>
</div>
<div class="small-12 medium-4 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.postal_code') %></strong>
        <%= model.address.postal_code %>
    </p>
</div>
<div class="small-12 medium-4 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.town') %></strong>
        <%= model.address.town %>
    </p>
</div>
<div class="small-12 medium-4 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.province') %></strong>
        <%= model.address.province %>
    </p>
</div>
<div class="small-12 medium-4 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.country') %></strong>
        <%= model.address.country %>
    </p>
</div>
 <div class="small-12 medium-6 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.phones') %></strong>
        <%= model.address.phones %>
    </p>
</div>
<div class="small-12 medium-6 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.email') %></strong>
        <%= model.address.email %>
    </p>
</div>

app/views/admin/organizations/_form.html.erb
<%= form_for [:admin, @organization], html: { class: 'organization-form' } do |f| %>

  <%= render 'admin/organizations/form/organization_errors', f: f %>
  <%= render 'admin/organizations/form/reference', f: f %>
  <%= render 'admin/organizations/form/data', f: f %>
  <%= render 'admin/organizations/form/legal_representant', f: f %>
  <%= render 'admin/organizations/form/notification_effect', f: f %>
  <%= render 'admin/organizations/form/user', f: f %>
  <%= render 'admin/organizations/form/lobby_data', f: f %>
  <%= render 'admin/organizations/form/represented_entities', f: f %>
  <%= render 'admin/organizations/form/agents', organization: @organization if !@organization.new_record? %>
  <%= render 'admin/organizations/form/terms', f: f %>
  <%= render 'admin/organizations/form/attachments', f: f %>
  <%= render 'admin/organizations/form/invalidate', f: f %>
  <% if params[:action] == "edit" %>
    <%= render 'admin/organizations/form/mailer', f: f %>
  <% end %>


  <div class="small-4 medium-3 large-2 column">
    <%= submit_tag t('backend.save'), class: "button radius success right" %>
  </div>

<% end %>

<%= javascript_include_tag 'organizations'%>

app/views/admin/organizations/edit.html.erb
<% if show_partial?('interests') %>
  <h1><%= t'backend.edit_title_interests' %></h1>
<% elsif show_partial?('agents') %>
  <h1><%= t'backend.edit_agents' %></h1>
<% else %>
  <h1>Editar Lobby</h1>
<% end %>
<%= render :partial => 'form' %>

app/views/admin/organizations/index.csv.erb
<%=

  exporter = OrganizationExporter.new true

  CSV.generate(col_sep: ';', encoding: 'ISO-8859-1') do |csv|
    csv << exporter.windows_headers

    @organizations.results.each do |organization|
      csv << exporter.windows_organization_row(organization)
    end
  end.html_safe
%>

app/views/admin/organizations/index.html.erb
<div class="row organizations-list">
  <div class="small-12 medium-8 column">
    <h1><%= t('backend.companies') %> (<%= @organizations.count %>)</h1>
    <%= link_to t('backend.export'), admin_organizations_path(format: :csv,params: params),class: "button tiny radius success" if current_user.admin? %>
  </div>
  <div class=" small-12 medium-4 column">
    <%= link_to t('backend.new_company'),new_admin_organization_path,class: "button radius warning right" if can? :create, Organization %>
  </div>
</div>

<%= render 'admin_search_form' %>
<div class="small-12 medium-8 columns">
  <%= page_entries_info @paginated_organizations, entry_name: t('backend.lobby') %>
  <%= paginate @paginated_organizations %>
</div>
<div class="small-12">
  <table class="small-12">
    <thead>
      <tr>
        <th><%= link_to_organizations_sorted_by :lobby %></th>
        <th><%= link_to_organizations_sorted_by :lobby_created_at  %></th>
        <th><%= link_to_organizations_sorted_by :lobby_renovation_at  %></th>
        <th><%= link_to_organizations_sorted_by :lobby_expired_at  %></th>
        <th><%= link_to_organizations_sorted_by :lobby_status %></th>
        <th><%= t('backend.lobby_management')%></th>
        <th><%= t('backend.actions')%></th>
      </tr>
    </thead>
    <tfoot>
      <tr>
        <th><%= t('backend.title')%></th>
        <th><%= t('backend.lobby_created_at')%></th>
        <th><%= t('backend.lobby_renovation_at')%></th>
        <th><%= t('backend.lobby_expired_at')%></th>
        <th><%= t('backend.lobby_status')%></th>
        <th><%= t('backend.lobby_management')%></th>
        <th><%= t('backend.actions')%></th>
      </tr>
    </tfoot>
    <tbody>
      <% @paginated_organizations.each do |organization| %>
        <% status = organization.status_type  %>
        <tr id="<%= dom_id(organization) %>" >
          <td>
            <%= "<i class='step fi-x size-24' style='color: red;'></i>".html_safe if !organization.set_expired_date.blank? && Time.zone.now > organization.set_expired_date && status != "Baja"%>   
            <%= link_to organization.fullname, admin_organization_path(organization) %>
          </td>
          <td><%= I18n.l organization.inscription_date, format: :short unless organization.inscription_date.blank? %></td>
          <td><%= I18n.l organization.renovation_date, format: :short unless organization.renovation_date.blank? %></td>
          <td><%= I18n.l organization.set_expired_date, format: :short unless status == "Baja" || organization.set_expired_date.blank? %></td>
          <td><%= status %></td>
          <td><%= organization.management_type %></td>
          <td>
            <%= link_to "<i class='step fi-torso size-24'></i>".html_safe,admin_organization_agents_path(organization),title: "Agentes" if current_user.admin? %>
            <%= link_to "<i class='step fi-eye size-24'></i>".html_safe,organization_path(organization, admin: "true"),target: :_blank,title: t('backend.lobby_show')  %>
            <%= link_to "<i class='step fi-page-edit size-24'></i>".html_safe,edit_admin_organization_path(organization),title: t('backend.edit') if can? :edit, organization%>
            <%= link_to " <i class='step fi-page-delete size-24'></i>".html_safe,admin_organization_path(organization),method: :delete,data: { confirm: t("backend.delete_confirm_lobby",name: organization.fullname) },title: t('backend.delete') if (can? :destroy, organization) && organization.status_type.to_s != t('backend.status_type.inactive') %>
            <% if organization.attachments.any? %>
              <%= link_to "<i class='step fi-archive size-24'></i>".html_safe,"#", title: t('backend.attachments_download'),class: "organization-attachments-dropdown-link",data: { dropdown: "#{organization_attachments_download_dropdown_id(organization)}" },aria: { controls: "#{organization_attachments_download_dropdown_id(organization)}" } %>
              <ul id="<%= organization_attachments_download_dropdown_id(organization) %>" class="organization-attachments-dropdown f-dropdown" data-dropdown-content aria-hidden="true" tabindex="-1">
                <% organization.attachments.each do |attachment| %>
                  <li><%= link_to "<i class='step fi-archive size-24'></i>#{attachment.file.original_filename}".html_safe,attachment.file.url, target: :_blank  %></li>
                <% end %>
              </ul>
            <% end %>
            <%#= link_to "<i class='step fi-archive size-24'></i>".html_safe,admin_organization_path(organization, format: :pdf), title: t('backend.get_pdf_identificator'), target: "blank"  %>          
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate @paginated_organizations %>

app/views/admin/organizations/new.html.erb
<div class="small-12 mt5 organizations-new">
  <h1><%= t('backend.new_organization_title')%></h1>
  <%= link_to t('backend.back'), admin_organizations_path , :class=> "button tiny radius" %>
</div>
<%= render "form" %>