config/routes.rb
Rails.application.routes.draw do

  resources :range_subventions
  resources :addresses
  resources :notification_effects
  get 'calendar/index'

  # Public resources
  root to: 'homepage#index', format: false
  
  
  get 'authorize' => 'auth#gettoken'
  get '/redirect', to: 'events#redirect', as: 'redirect'
  get '/callback', to: 'events#callback', as: 'callback'
  get '/calendars', to: 'events#calendars', as: 'calendars'

  get '/lang/:lang', to: 'application#change_language', as: 'change_language'
  get '/show/:id', to: 'visitors#show', as: 'show'
  get '/update_holders', to: 'visitors#update_holders', as: 'update_holders'
  get '/inicio.do', to: 'uweb_access#uweb_sign_in'
  get '/agenda/:holder/:full_name', to: 'visitors#agenda', as: 'agenda'

  get '/faq', to: 'questions#index', as: 'faq'
  get '/websitemap', to: 'static_pages#websitemap', as: 'websitemap'

  post '/ws/agends', to: 'ws/agends#generic'
  post '/ws/agends/:personal_code', to: 'ws/agends#holder'

  resources :statistics, only: [:index]
  resources :statistics do
    get :lobbies, on: :collection
  end

  get '/code_of_conduct', to: 'static_pages#code_of_conduct', as: 'code_of_conduct'
  get '/accessibility', to: 'static_pages#accessibility', as: 'accessibility'

  get '/homepage', to: 'homepage#index', as: 'homepage'
  get 'registration_lobbies/index'
  get '/registration_lobbies', to: 'registration_lobbies#index', as: 'registration_lobbies'
  get '/visitors', to: 'visitors#index', as: 'visitors'
  get '/export_events', to: 'visitors#export_events', as: 'visitors_export_events'

  # Admin
  get "/admin", to: 'events#index', as: 'admin'
  
  #namespace :api do
    wash_out :servicio_integracion_bareg
  #end
  

  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :events do
    get :download, on: :collection
    get :clone, on: :member
    get :export_outlook, on: :member
    get :get_calendars, on: :member
  end
  
 
  resources :areas
  resources :activities
  resources :infringement_emails, only: [:new, :create]
  resources :holders do 
    get :active, on: :collection
    get :mail, on: :member
    post :send_mail, on: :member
    get :export_all, on: :collection
    get :search, on: :collection
  end


  namespace :admin do
    resources :notifications, except: [:index, :new, :create, :destroy] do 
      get :active, on: :collection
      get :historic, on: :collection
      get :pre_recover, on: :member
      post :recover, on: :member
      get :pre_canceled, on: :member
      post :canceled, on: :member
      get :permited, on: :member
      get :manually_permited, on: :member
      get :recover_origin, on: :member
      post :update_notification, on: :member
    end
    resources :exports
    resources :parametrizations, only: [:index] do
      post :change_view, on: :collection
      post :length_event_description, on: :collection
      post :send_email, on: :collection
      post :update_configure_text, on: :member
      get :download_log
    end
    resources :manage_emails
    resources :users do 
      get :revert, on: :member
      get :assign_holder, on: :collection
      get :export_manages, on: :collection
      get :uweb, on: :collection
    end
    get 'passwords/edit', to: 'passwords#edit', as: 'edit_password'
    match 'passwords/update', to: 'passwords#update', as: 'update_password', via: [:patch, :put]
    resources :organizations do
      resources :agents
      resources :organization_interests, only: [:index]
      match 'interests_update', to: 'organization_interests#update', as: 'interests_update', via: [:patch, :put]
    end
    resources :organizations_links
    resources :questions
    post 'order_questions', to: 'questions#order', as: 'order_questions'

    resources :newsletters do
      member do
        post :deliver
      end
      get :users, on: :collection
    end
  end

  resources :positions do
    get :autocomplete_position_title, :on => :collection
  end
  get '/organizations/edit', to: 'organizations#edit', as: 'edit_organization'
  get '/organizations/destroy', to: 'organizations#destroy', as: 'destroy_organization'
  get '/organizations/new', to: 'organizations#new', as: 'new_organization'
  resources :organizations, except: [:new, :edit, :destroy] do
    get :autocomplete_organization_name, :on => :collection
    resources :represented_entities, only: :index, format: :json
    resources :agents, only: :index, format: :json
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get '*path' => redirect { |p, req| req.flash[:alert] = "No se encuentra la ruta especificada"; '/' } unless Rails.env.development?

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  has_many :newsletters_interests, dependent: :destroy
  has_many :interests, through: :newsletters_interests, dependent: :destroy
  has_many :organizations_newsletters, dependent: :destroy
  belongs_to :interest


  validates :subject, presence: true
  validates :body, presence: true
  #validates :interest_id, presence: true
  validates :interests, presence: true

  def list_of_recipient_emails
    list_of_mails = []
    hash_of_recipient_emails.each do |organization|
      list_of_mails << organization[:email]
    end
    list_of_mails << admin_email
  end

  def hash_of_recipient_emails
    hash_emails = []
    if self.draft?
      #organizations =Organization.where(organization_interests: { interest: interest }).joins(:organization_interests) #, communication_term: true)
      
      
      organizations =Organization.joins(:organization_interests).where("organizations.id = organization_interests.organization_id AND organization_interests.interest_id IN (?)", self.interest_ids)
      
      organizations.each do |organization|
        if organization.user_email.blank?
          if !organization.address.email.blank?
            hash_emails.push({:id => organization.id,
              :name => organization.fullname, 
              :email => organization.address.email })
          else !organization.email.blank?
            hash_emails.push({:id => organization.id,
              :name => organization.fullname, 
              :email => organization.email })
          end
        else
          hash_emails.push({:id => organization.id,
            :name => organization.fullname, 
            :email => organization.user_email })
        end
      end
    else
      registered_organizations = self.organizations_newsletters
      registered_organizations.each do |organization_newsletter|
        hash_emails.push({:id => organization_newsletter.organization_id, 
          :name => organization_newsletter.organization.fullname, 
          :email => organization_newsletter.email_send })
      end
    end

    hash_emails.uniq
  end

  def admin_email
    "registrodelobbies@madrid.es"
  end

  def draft?
    sent_at.nil?
  end

  def get_interests
    interest = ""
    self.interests.each {|i| interest = interest + (interest.blank? ? i.name + "." : "<br>" + i.name + ".") }      
    interest
  end

  def deliver
    hash_of_recipient_emails.each do |recipient_email|
      if valid_email?(recipient_email[:email])
        begin
          UserMailer.newsletter(self, recipient_email[:email]).deliver_now

          organization_send_newsletter({
            :organization_id => recipient_email[:id],
            :newsletter_id => self.id,
            :email_send => recipient_email[:email],
          })
          log_delivery(recipient_email[:email])
        rescue => e
       
          begin
            Rails.logger.error("SMS-ERROR: #{e}")
          rescue
          end
          log_delivery(recipient_email[:email], :email_error)
        end
      end
    end
    if valid_email?( admin_email)
      begin
        UserMailer.newsletter(self,  admin_email).deliver_now

        log_delivery( admin_email)
      rescue => e
        begin
          Rails.logger.error("SMS-ERROR: #{e}")
        rescue
        end
        log_delivery( admin_email, :email_error)
      end
    end
  end

  private

    def valid_email?(email)
      email.match(/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i)
    end

    def organization_send_newsletter(attributtes)
      organizations_newsletter=OrganizationsNewsletter.new(attributtes)
      organizations_newsletter.save
    end

    def log_delivery(recipient_email, action=:email)
      if recipient_email == admin_email
        Log.activity(nil, "admin_email", self)
      else
        organization = Organization.where(email: recipient_email).first
        Log.activity(organization, action, self)
      end
    end
end

app/controllers/admin/newsletters_controller.rb
module Admin
  class NewslettersController < AdminController
    load_and_authorize_resource
    before_action :load_options
    before_action :load_newsletter, only: [:show,:edit,:update,:destroy,:deliver]


    def index
      @newsletters = Newsletter.all
    rescue => e
      begin
        Rails.logger.error("COD-00001: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def show
      @recipients_count = @newsletter.list_of_recipient_emails.count
      @destinataries = @newsletter.hash_of_recipient_emails
      @title= @newsletter.draft? ? I18n.t("backend.newsletters.show.title") : I18n.t("backend.newsletters.show.title_after")
    rescue => e
      begin
        Rails.logger.error("COD-00002: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def new
      @newsletter = Newsletter.new
    rescue => e
      begin
        Rails.logger.error("COD-00003: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def create
      aux = newsletter_params
      aux[:interest_ids] = aux[:interest_ids].reject(&:blank?)

    
      @newsletter = Newsletter.new(aux)
      @newsletter.interest_id = aux[:interest_ids].try(:first)

      if @newsletter.save
        notice = t("backend.newsletters.create_success")
        redirect_to [:admin, @newsletter], notice: notice
      else
        render :new
      end
    rescue => e
      begin
        Rails.logger.error("COD-00004: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def edit
    rescue => e
      begin
        Rails.logger.error("COD-00005: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def update   
      aux = newsletter_params      
      aux[:interest_ids] = aux[:interest_ids].reject(&:blank?)
      @newsletter.interest_id = aux[:interest_ids].try(:first) if @newsletter.interest_id.blank?
      if @newsletter.update(aux)
        redirect_to [:admin, @newsletter], notice: t("backend.newsletters.update_success")
      else
        render :edit
      end
    rescue => e
      begin
        Rails.logger.error("COD-00006: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def destroy
      @newsletter.destroy

      redirect_to admin_newsletters_path, notice: t("backend.newsletters.delete_success")
    rescue => e
      begin
        Rails.logger.error("COD-00007: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def deliver
      if @newsletter.valid?
        @newsletter.deliver
        @newsletter.update(sent_at: Time.current)
        flash[:notice] = t("backend.newsletters.send_success")
      else
        flash[:error] = t("admin.segment_recipient.invalid_recipients_segment")
      end

      redirect_to [:admin, @newsletter]
    rescue => e
      begin
        Rails.logger.error("COD-00008: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    private
      def load_newsletter
        @newsletter = Newsletter.find(params[:id])
      end

      def newsletter_params
        params.require(:newsletter).permit(:subject, :segment_recipient, :from, :body, { interest_ids: [] },)
      end

      def load_options
        @hash_interest={}
        Interest.all.where("name != 'Otros'").order(:name).each do |interest|
          @hash_interest.merge!({interest.name=>interest.id}) if interest.id != 0
        end
        @hash_interest.merge!({Interest.find_by(name: "Otros").name=>Interest.find_by(name: "Otros").id})
      end
  end
end

app/views/admin/newsletters/_form.html.erb
<%= form_for [:admin, @newsletter] do |f| %>
  <%= f.hidden_field :interest_id, :value => 0 %>
  

  <% if @newsletter.errors.any? %>
    <div class="panel alert-box alert radius">
      <strong>
        <%= t('activerecord.errors.template.header',
            :model => Newsletter.model_name.human,
            :count => @newsletter.errors.count) %></strong>
      <ul>
        <% @newsletter.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <label><%= t('backend.newsletters.new.category') %></label>
  <%= f.select :interest_ids,Interest.all.collect { |x| [x.name, x.id]}, {:include_blank => false}, {multiple: true} %>

  <%= f.label :subject, t('backend.newsletters.new.subject') %>
  <%= f.text_field :subject %>

  <%= f.label :body, t('backend.newsletters.new.body') %>
  <%= f.text_area :body, rows: 10 %>

  <div class="margin-top">
    <%= f.submit class: "button success" %>
  </div>
<% end %>

app/views/admin/newsletters/_organizations.html.erb
<div class="row">
  <div class="small-12 column">
    <strong><%= t("backend.newsletters.show.segment_recipient") %></strong>
    <p class="help-text" id="phase-description-help-text">
      <%= t("backend.newsletters.show.admin_email", email: admin_email ) %>
    </p>
  </div>
</div>
<div class="row">
  <table id="newsletters" class="display margin-top" cellpadding="0" width="100%">
    <thead>
    <tr>
      <th class="small-7" ><%= t("backend.newsletters.show.organization") %></th>
      <th><%= t("backend.newsletters.show.email") %></th>
    </tr>
    </thead>
    <tfoot>
    <tr>
      <th class="small-7"><%= t("backend.newsletters.show.organization") %></th>
      <th><%= t("backend.newsletters.show.email") %></th>
    </tr>
    </tfoot>
    <tbody>
    <% organizations.each do |destined| %>
      <tr class="small-7">
        <td>
          <%= destined[:name] %>
        </td>
        <td>
          <%= destined[:email] %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/newsletters/edit.html.erb
<%= link_to t('backend.back'), 
    admin_newsletters_path , 
    class: "button tiny radius" %>
    
<h2><%= t("backend.newsletters.edit.title") %></h2>

<%= render "form" %>

app/views/admin/newsletters/index.html.erb
<div class="row">
  <h1>
    <%= t("backend.newsletters.index.title") %> (<%= @newsletters.count %>)
    <%= link_to t("backend.newsletters.index.new_newsletter"), new_admin_newsletter_path, :class => "button radius warning right" if can? :create, Newsletter %>
  </h1>
</div>

<div class="row">
  <% if @newsletters.any? %>
  <table id="newsletters" class="display" cellpadding="0" width="100%">
    <thead>
    <tr>
      <th class="small-6"><%= t("backend.newsletters.index.subject") %></th>
      <th><%= t("backend.newsletters.index.sent") %></th>
      <th><%= t("backend.newsletters.index.actions") %></th>
    </tr>
    </thead>
    <tfoot>
    <tr>
      <th class="small-6"><%= t("backend.newsletters.index.subject") %></th>
      <th><%= t("backend.newsletters.index.sent") %></th>
      <th><%= t("backend.newsletters.index.actions") %></th>
    </tr>
    </tfoot>
    <tbody>
    <% @newsletters.order(created_at: :desc).each do |newsletter| %>
      <tr id="<%= dom_id(newsletter) %>" class="newsletter">
        <td>
          <%= newsletter.subject %>
        </td>
        <td>
          <% if newsletter.draft? %>
            <%= t("backend.newsletters.index.draft") %>
          <% else %>
            <%= l newsletter.sent_at.to_date %>
          <% end %>
        </td>
        <td>
          <%= link_to admin_newsletter_path(newsletter),
                      title: t("backend.newsletters.index.preview") do %>
            <i class="step fi-eye size-24"></i>
          <% end %>
          <%= link_to edit_admin_newsletter_path(newsletter), title: t("backend.newsletters.index.edit") do %>
              <i class="step fi-page-edit size-24"></i>
          <% end if can? :edit, Newsletter %>
          <%= link_to admin_newsletter_path(newsletter), method: :delete, data: { confirm: t("backend.confirm") }, title: t("backend.newsletters.index.delete") do%>
              <i class="step fi-page-delete size-24"></i>
          <% end if can? :delete, Newsletter%>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <% else %>
  <div data-alert class="alert-box radius primary margin-top clear">
    <%= t("backend.newsletters.index.empty_newsletters") %>
  </div>
  <% end %>
</div>

app/views/admin/newsletters/new.html.erb
<%= link_to t('backend.back'), 
    admin_newsletters_path , 
    class: "button tiny radius" %>
    
<h2><%= t("backend.newsletters.new.title") %></h2>

<%= render "form" %>

app/views/admin/newsletters/show.html.erb
<div class="row">
  <%= link_to t('backend.back'),
      admin_newsletters_path ,
      class: "button tiny radius" %>
</div>
<div class="row">
  <h2><%= @title %></h2>
</div>
<div class="row">
  <div class="column callout highlight">
    <div class="row">
      <div class="small-12 medium-2 column">
        <strong><%= t("backend.newsletters.show.sent_at") %></strong><br>
        <% if @newsletter.draft? %>
          <%= t("backend.newsletters.index.draft") %>
        <% else %>
          <%= l @newsletter.sent_at.to_date %>
        <% end %>
      </div>
      <div class="small-12 medium-4 column">
        <strong><%= t("backend.newsletters.show.subject") %></strong><br>
        <%= @newsletter.subject %>
      </div>
      <div class="small-12 medium-6 column">
        <strong><%= t("backend.newsletters.show.category") %></strong><br>
        <%= !@newsletter.try(:interests).blank? ? @newsletter.get_interests.html_safe : @newsletter.try(:interest) %>
      </div>
    </div>
    <div class="row">
      <div class="small-12 column margin-top">
        <strong><%= t("backend.newsletters.show.segment_recipient") %></strong><br>
        <%= t("backend.newsletters.show.affected_users", n: @recipients_count) %><br>
      </div>
    </div>
  </div>
</div>

<%= render partial: "organizations", locals: {organizations: @destinataries, admin_email: @newsletter.admin_email}%>

<div class="row">
  <div class="small-12 column">
    <strong><%= t("backend.newsletters.show.body") %></strong>
    <p class="help-text" id="phase-description-help-text">
      <%= t("backend.newsletters.show.body_help_text") %>
    </p>
  </div>
</div>
<div class="row">
  <div class="newsletter-body-content">
    <table cellpadding="0" cellspacing="0" border="0" style="background: #fff; margin: 0 auto; max-width: 800px; width:100%;">
      <thead>
        <tr>
          <th style="background: #013df5;">
            <%= image_tag 'logo-email.jpg', alt:'¡Madrid' %>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <%= render file: "app/views/user_mailer/newsletter.html.erb" %>
        </tr>
        <tr>
          <td>
            <p><%= t('mailers.footer_newsletter') %>
            <p><%= t('mailers.footer', year: Date.current.year) %></p>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<% if @newsletter.draft? %>
<div class="row">
  <div class="samll-12 column margin-top">
    <%= link_to t("backend.newsletters.show.send"),
                deliver_admin_newsletter_path(@newsletter),
                "data-alert": t("backend.newsletters.show.send_alert", n: @recipients_count),
                method: :post,
                id: "js-send-newsletter-alert",
                class: "button success" %>
  </div>
</div>
<% end %>